In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import glob
import os

%matplotlib inline

In [2]:
file = os.path.join('C:\\Users\\saras\\Documents\\NSS\\Capstone\\final_capstone\\Data\\', 'tornado_*.csv')
file = glob.glob(file)
tornado_years = pd.concat(map(pd.read_csv,file), ignore_index = True)
tornado_years

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,...,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56
0,10063615,ST. LOUIS CO.,,1/3/1950,1100,Tornado,0,F3,0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,10009710,MADISON CO.,,1/3/1950,1110,Tornado,0,F3,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,10009711,MONTGOMERY CO.,,1/3/1950,1155,Tornado,0,F3,0,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10086808,VAN WERT CO.,,1/3/1950,1600,Tornado,0,F1,0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,9981922,POLK CO.,,1/13/1950,525,Tornado,0,F3,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35238,955453,LOGAN CO.,STERLING,5/23/2021,1449,Tornado,,EF1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35239,952078,PERKINS CO.,USTA,5/23/2021,1450,Tornado,,EFU,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35240,952080,CUSTER CO.,PRINGLE,5/23/2021,1455,Tornado,,EF1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35241,952079,PERKINS CO.,MEADOW,5/23/2021,1458,Tornado,,EFU,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35242,952081,CUSTER CO.,CUSTER,5/23/2021,1504,Tornado,,EF1,0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
tornado_years = tornado_years.drop(tornado_years.columns[38:],axis=1)

In [5]:
tornado_years

,EVENT_ID,CZ_NAME_STR,BEGIN_LOCATION,BEGIN_DATE,BEGIN_TIME,EVENT_TYPE,MAGNITUDE,TOR_F_SCALE,DEATHS_DIRECT,INJURIES_DIRECT,DAMAGE_PROPERTY_NUM,DAMAGE_CROPS_NUM,STATE_ABBR,CZ_TIMEZONE,MAGNITUDE_TYPE,EPISODE_ID,CZ_TYPE,CZ_FIPS,WFO,INJURIES_INDIRECT,DEATHS_INDIRECT,SOURCE,FLOOD_CAUSE,TOR_LENGTH,TOR_WIDTH,BEGIN_RANGE,BEGIN_AZIMUTH,END_RANGE,END_AZIMUTH,END_LOCATION,END_DATE,END_TIME,BEGIN_LAT,BEGIN_LON,END_LAT,END_LON,EVENT_NARRATIVE,EPISODE_NARRATIVE
0,10063615,ST. LOUIS CO.,,1/3/1950,1100,Tornado,0,F3,0,3,2500000.0,0,MO,CST,,,C,189,,0,0,,,6.2,150,0,,0,,,1/3/1950,1100,38.77,-90.22,38.82,-90.12,NaN,NaN
1,10009710,MADISON CO.,,1/3/1950,1110,Tornado,0,F3,0,0,250000.0,0,IL,CST,,,C,119,,0,0,,,3.3,100,0,,0,,,1/3/1950,1110,38.82,-90.1,38.83,-90.03,NaN,NaN
2,10009711,MONTGOMERY CO.,,1/3/1950,1155,Tornado,0,F3,0,3,250000.0,0,IL,CST,,,C,135,,0,0,,,3.6,130,0,,0,,,1/3/1950,1155,39.1,-89.3,39.12,-89.23,NaN,NaN
3,10086808,VAN WERT CO.,,1/3/1950,1600,Tornado,0,F1,0,1,25000.0,0,OH,CST,,,C,161,,0,0,,,0.1,33,0,,0,,,1/3/1950,1600,40.88,-84.58,,,NaN,NaN
4,9981922,POLK CO.,,1/13/1950,525,Tornado,0,F3,1,1,2500.0,0,AR,CST,,,C,113,,0,0,,,0.6,17,0,,0,,,1/13/1950,525,34.4,-94.37,,,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35238,955453,LOGAN CO.,STERLING,5/23/2021,1449,Tornado,,EF1,0,0,0.0,0,CO,MST-7,,158058,C,75,BOU,0,0,County Official,,0.1,50,3,ESE,3,ESE,STERLING,5/23/2021,1500,40.61,-103.14,40.61,-103.14,A tornado touched down and knocked power poles...,"Severe thunderstorms developed across Lincoln,..."
35239,952078,PERKINS CO.,USTA,5/23/2021,1450,Tornado,,EFU,0,0,0.0,0,SD,MST-7,,157459,C,105,UNR,0,0,Storm Chaser,,2.13,10,6,NNW,8,NNW,USTA,5/23/2021,1455,45.3,-102.19,45.33,-102.2,"A tornado formed west of SD Highway 73, about ...",A supercell thunderstorm tracked northward acr...
35240,952080,CUSTER CO.,PRINGLE,5/23/2021,1455,Tornado,,EF1,0,0,0.0,0,SD,MST-7,,157460,C,33,UNR,0,0,NWS Storm Survey,,6.6,20,4,N,5,ESE,CUSTER,5/23/2021,1505,43.67,-103.6,43.74,-103.51,A tornado was reported about five miles south ...,A line of severe thunderstorms developed over ...
35241,952079,PERKINS CO.,MEADOW,5/23/2021,1458,Tornado,,EFU,0,0,0.0,0,SD,MST-7,,157459,C,105,UNR,0,0,Storm Chaser,,4.26,10,10,S,6,S,MEADOW,5/23/2021,1505,45.38,-102.22,45.44,-102.24,A tornado formed shortly after a previous torn...,A supercell thunderstorm tracked northward acr...
35242,952081,CUSTER CO.,CUSTER,5/23/2021,1504,Tornado,,EF1,0,0,0.0,0,SD,MST-7,,157460,C,33,UNR,0,0,NWS Storm Survey,,5.86,10,1,NE,7,ENE,CUSTER,5/23/2021,1513,43.78,-103.58,43.81,-103.47,A tornado touched down just northeast of Custe...,A line of severe thunderstorms developed over ...